version: "3"
services:
  app:
    image: latiendadelbebe
    container_name: latiendadelbebe
    restart: always
    ports:
      - 127.0.0.1:8001:80
    volumes:
      - upload:/app/dist/upload
volumes:
  upload: